source 'https://rubygems.org'

# gem 'aws-sdk',     '~>3.0.1'
gem 'aws-sdk-ec2', '~>1.21.0'
gem 'aws-sdk-autoscaling', '~>1.4.0'
gem 'aws-sdk-elasticloadbalancing', '~>1.1.0'
gem 'aws-sdk-elasticloadbalancingv2', '~>1.6.0'

gem 'bosh_common', '1.3262.24.0'
gem 'bosh_cpi',    '~>2.4'

group :development, :test do
  gem 'aws-sdk-iam', '~>1.3.0'
  gem 'netaddr'
  gem 'pry-byebug', '~>3.4'
  gem 'rspec',      '~>3.5'
  gem 'rake',       '~>12.0'
  gem 'webmock'
end
